// fio.proto -- wire-format schema for fio.Info metadata.
//
// SPDX-License-Identifier: GPL-2.0
//
// (c) 2024- Sudhi Herle <sudhi@herle.net>
//
// Licensing Terms: GPLv2
//
// If you need a commercial license for this work, please contact
// the author.
//
// This software does not come with any express or implied
// warranty; it is provided "as is". No claim is made to its
// suitability for any purpose.
//
// Generated Go code lands in ./internal/pb/ via scripts/gen-proto.sh.
// Regenerate with:
//
//     scripts/gen-proto.sh proto/fio.proto
//
// Field-number reservation policy:
//   1..16   in use today; 1-byte tag; never renumber.
//   17..31  reserved for future stat(2)-ish additions (birthtime,
//           st_flags, inode generation, encryption flags, ...).
//           Still 1-byte tag.
//   32..127 1-byte tag but repurposing needs a compat bump.
//   128+    2-byte tag; use for rarely-set optional blobs.
//
// Always emit `reserved` ranges for anything we remove. Never
// reuse a number.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/fio.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wire-format metadata for a file-system entry (mirrors fio.Info).
//
// Field names match the Go-side fio.Info field names exactly
// (Ino, Siz, Blocks, Dev, Rdev, Mod, Uid, Gid, Nlink, Atim, Mtim,
// Ctim, Path), so the hand-written toProto / fromProto converters
// read as straight field copies.
type Info struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity.
	Ino  uint64 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`
	Dev  uint64 `protobuf:"varint,2,opt,name=dev,proto3" json:"dev,omitempty"`
	Rdev uint64 `protobuf:"varint,3,opt,name=rdev,proto3" json:"rdev,omitempty"`
	// Content size. int64 matches Go; sparse files may legitimately
	// be large but never negative.
	Siz int64 `protobuf:"varint,4,opt,name=siz,proto3" json:"siz,omitempty"`
	// Go's fs.FileMode bits captured verbatim. The high bits carry
	// Go-specific meaning (ModeDir, ModeSymlink, ModeIrregular, ...);
	// a non-Go consumer decoding this field must re-interpret.
	Mod uint32 `protobuf:"varint,5,opt,name=mod,proto3" json:"mod,omitempty"`
	// Ownership.
	Uid   uint32 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid   uint32 `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	Nlink uint32 `protobuf:"varint,8,opt,name=nlink,proto3" json:"nlink,omitempty"`
	// Times as signed nanoseconds since Unix epoch. Signed so
	// pre-1970 values survive. Range ±292 years covers any
	// timestamp a kernel will issue.
	Atim int64 `protobuf:"varint,9,opt,name=atim,proto3" json:"atim,omitempty"`
	Mtim int64 `protobuf:"varint,10,opt,name=mtim,proto3" json:"mtim,omitempty"`
	Ctim int64 `protobuf:"varint,11,opt,name=ctim,proto3" json:"ctim,omitempty"`
	// File path. The JunkPath MarshalFlag strips to basename in
	// the converter before this field is populated.
	Path string `protobuf:"bytes,12,opt,name=path,proto3" json:"path,omitempty"`
	// Extended attributes. `bytes` (not `string`): proto3 string
	// must be valid UTF-8, but raw xattr payloads (e.g. POSIX ACL
	// blobs, security.capability) are arbitrary octet sequences.
	//
	// Deterministic ordering: the converter sorts entries by key
	// before marshaling so the bytes are stable across runs -
	// required for content-addressed storage / hash comparisons.
	Entries []*XattrEntry `protobuf:"bytes,13,rep,name=entries,proto3" json:"entries,omitempty"`
	// Allocated 512-byte block count (POSIX st_blocks). The unit is
	// standardized: every Unix kernel reports st_blocks in 512-byte
	// chunks regardless of the underlying filesystem block size.
	// Multiply by 512 (or use fio.Info.DiskBytes()) for bytes-on-disk.
	Blocks        int64 `protobuf:"varint,14,opt,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_proto_fio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_proto_fio_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *Info) GetDev() uint64 {
	if x != nil {
		return x.Dev
	}
	return 0
}

func (x *Info) GetRdev() uint64 {
	if x != nil {
		return x.Rdev
	}
	return 0
}

func (x *Info) GetSiz() int64 {
	if x != nil {
		return x.Siz
	}
	return 0
}

func (x *Info) GetMod() uint32 {
	if x != nil {
		return x.Mod
	}
	return 0
}

func (x *Info) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Info) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Info) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *Info) GetAtim() int64 {
	if x != nil {
		return x.Atim
	}
	return 0
}

func (x *Info) GetMtim() int64 {
	if x != nil {
		return x.Mtim
	}
	return 0
}

func (x *Info) GetCtim() int64 {
	if x != nil {
		return x.Ctim
	}
	return 0
}

func (x *Info) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Info) GetEntries() []*XattrEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Info) GetBlocks() int64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

type XattrEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XattrEntry) Reset() {
	*x = XattrEntry{}
	mi := &file_proto_fio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XattrEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XattrEntry) ProtoMessage() {}

func (x *XattrEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XattrEntry.ProtoReflect.Descriptor instead.
func (*XattrEntry) Descriptor() ([]byte, []int) {
	return file_proto_fio_proto_rawDescGZIP(), []int{1}
}

func (x *XattrEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *XattrEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_fio_proto protoreflect.FileDescriptor

const file_proto_fio_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/fio.proto\x12\x0fopencoff.fio.v1\"\xdf\x02\n" +
	"\x04Info\x12\x10\n" +
	"\x03ino\x18\x01 \x01(\x04R\x03ino\x12\x10\n" +
	"\x03dev\x18\x02 \x01(\x04R\x03dev\x12\x12\n" +
	"\x04rdev\x18\x03 \x01(\x04R\x04rdev\x12\x10\n" +
	"\x03siz\x18\x04 \x01(\x03R\x03siz\x12\x10\n" +
	"\x03mod\x18\x05 \x01(\rR\x03mod\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\a \x01(\rR\x03gid\x12\x14\n" +
	"\x05nlink\x18\b \x01(\rR\x05nlink\x12\x12\n" +
	"\x04atim\x18\t \x01(\x03R\x04atim\x12\x12\n" +
	"\x04mtim\x18\n" +
	" \x01(\x03R\x04mtim\x12\x12\n" +
	"\x04ctim\x18\v \x01(\x03R\x04ctim\x12\x12\n" +
	"\x04path\x18\f \x01(\tR\x04path\x125\n" +
	"\aentries\x18\r \x03(\v2\x1b.opencoff.fio.v1.XattrEntryR\aentries\x12\x16\n" +
	"\x06blocks\x18\x0e \x01(\x03R\x06blocksJ\x04\b\x0f\x10 R\tbirthtimeR\x05flagsR\n" +
	"generation\"4\n" +
	"\n" +
	"XattrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05valueB(Z&github.com/opencoff/go-fio/internal/pbb\x06proto3"

var (
	file_proto_fio_proto_rawDescOnce sync.Once
	file_proto_fio_proto_rawDescData []byte
)

func file_proto_fio_proto_rawDescGZIP() []byte {
	file_proto_fio_proto_rawDescOnce.Do(func() {
		file_proto_fio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fio_proto_rawDesc), len(file_proto_fio_proto_rawDesc)))
	})
	return file_proto_fio_proto_rawDescData
}

var file_proto_fio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fio_proto_goTypes = []any{
	(*Info)(nil),       // 0: opencoff.fio.v1.Info
	(*XattrEntry)(nil), // 1: opencoff.fio.v1.XattrEntry
}
var file_proto_fio_proto_depIdxs = []int32{
	1, // 0: opencoff.fio.v1.Info.entries:type_name -> opencoff.fio.v1.XattrEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_fio_proto_init() }
func file_proto_fio_proto_init() {
	if File_proto_fio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fio_proto_rawDesc), len(file_proto_fio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_fio_proto_goTypes,
		DependencyIndexes: file_proto_fio_proto_depIdxs,
		MessageInfos:      file_proto_fio_proto_msgTypes,
	}.Build()
	File_proto_fio_proto = out.File
	file_proto_fio_proto_goTypes = nil
	file_proto_fio_proto_depIdxs = nil
}
